import { TodoNote, ColorStyle } from './types';

export const COLORS_PALETTE: Record<string, ColorStyle> = {
  zinc: {
    bg: 'bg-[#fafaf9]',
    border: 'border-zinc-300/90 shadow-[4px_4px_0px_0px_#d4d4d8]',
    accent: 'text-zinc-650 focus:ring-zinc-500',
    dot: 'bg-zinc-500',
    label: 'Warm SketchPad',
    saveBtn: 'bg-zinc-900 hover:bg-zinc-800 text-white shadow-zinc-200/50',
    saveBtnLight: 'bg-zinc-150 hover:bg-zinc-200 text-zinc-800 border-zinc-300',
    tape: 'bg-zinc-200/70 border-zinc-300',
    badge: 'bg-zinc-100/80 text-zinc-800 border-zinc-300/70',
  },
  amber: {
    bg: 'bg-[#fefce8]',
    border: 'border-yellow-350 shadow-[4px_4px_0px_0px_#fde047]',
    accent: 'text-amber-700 focus:ring-amber-500',
    dot: 'bg-amber-500',
    label: 'Sticky Daffodil',
    saveBtn: 'bg-yellow-600 hover:bg-yellow-750 text-white shadow-yellow-200/30',
    saveBtnLight: 'bg-yellow-100 hover:bg-yellow-200 text-yellow-950 border-yellow-250',
    tape: 'bg-yellow-200/60 border-yellow-350',
    badge: 'bg-yellow-100/80 text-yellow-900 border-yellow-200/70',
  },
  blue: {
    bg: 'bg-[#f0f9ff]',
    border: 'border-sky-300 shadow-[4px_4px_0px_0px_#bae6fd]',
    accent: 'text-sky-700 focus:ring-sky-500',
    dot: 'bg-sky-500',
    label: 'Sky Blueprint',
    saveBtn: 'bg-sky-600 hover:bg-sky-750 text-white shadow-sky-200/30',
    saveBtnLight: 'bg-sky-100 hover:bg-sky-250 text-sky-950 border-sky-300',
    tape: 'bg-sky-200/60 border-sky-300',
    badge: 'bg-sky-100/90 text-sky-900 border-sky-200/80',
  },
  emerald: {
    bg: 'bg-[#f0fdf4]',
    border: 'border-emerald-300 shadow-[4px_4px_0px_0px_#a7f3d0]',
    accent: 'text-emerald-700 focus:ring-emerald-500',
    dot: 'bg-emerald-500',
    label: 'Fresh Mint leaf',
    saveBtn: 'bg-emerald-600 hover:bg-emerald-750 text-white shadow-emerald-200/30',
    saveBtnLight: 'bg-emerald-100 hover:bg-emerald-250 text-emerald-950 border-emerald-300',
    tape: 'bg-emerald-200/60 border-emerald-300',
    badge: 'bg-emerald-100/90 text-emerald-900 border-emerald-200/80',
  },
  purple: {
    bg: 'bg-[#faf5ff]',
    border: 'border-purple-300 shadow-[4px_4px_0px_0px_#e9d5ff]',
    accent: 'text-purple-700 focus:ring-purple-500',
    dot: 'bg-purple-500',
    label: 'Pastel Lavender',
    saveBtn: 'bg-purple-600 hover:bg-purple-750 text-white shadow-purple-200/30',
    saveBtnLight: 'bg-purple-100 hover:bg-purple-250 text-purple-950 border-purple-300',
    tape: 'bg-purple-200/60 border-purple-300',
    badge: 'bg-purple-100/90 text-purple-900 border-purple-200/80',
  },
  rose: {
    bg: 'bg-[#fff5f5]',
    border: 'border-rose-300 shadow-[4px_4px_0px_0px_#fecdd3]',
    accent: 'text-rose-700 focus:ring-rose-500',
    dot: 'bg-rose-500',
    label: 'Blossom Pink',
    saveBtn: 'bg-rose-600 hover:bg-rose-750 text-white shadow-rose-200/30',
    saveBtnLight: 'bg-rose-100 hover:bg-rose-250 text-rose-950 border-rose-300',
    tape: 'bg-rose-200/60 border-rose-300',
    badge: 'bg-rose-100/90 text-rose-900 border-rose-200/80',
  },
};

export const INITIAL_NOTES: TodoNote[] = [
  {
    id: 'note-1',
    title: '💡 UI Redesign Core Milestones',
    content: 'Review and implement atomic guidelines for responsive mobile breakpoints. Keep typography clean and focused.',
    checklist: [
      { id: 'sub-1', text: 'Define standard typographic tracking scales', isCompleted: true },
      { id: 'sub-2', text: 'Perform visual accessibility contrast checks', isCompleted: false },
      { id: 'sub-3', text: 'Prune complex nested layouts and sidebar menus', isCompleted: false },
    ],
    isPinned: true,
    colorName: 'blue',
    createdAt: '2026-06-09',
    updatedAt: '2026-06-09',
  },
  {
    id: 'note-2',
    title: '🛒 Weekly Fresh Grocery List',
    content: 'Stock up for workspace snacks. Prefer organic and healthy ingredients where possible.',
    checklist: [
      { id: 'sub-4', text: 'Cold brew concentrate drinks', isCompleted: true },
      { id: 'sub-5', text: 'Salted nuts & mixed seeds', isCompleted: true },
      { id: 'sub-6', text: 'Fresh seasonal berries', isCompleted: false },
    ],
    isPinned: false,
    colorName: 'amber',
    createdAt: '2026-06-08',
    updatedAt: '2026-06-08',
  },
  {
    id: 'note-3',
    title: '📝 Content Writing Strategy Notes',
    content: 'Keep all internal articles Conversational, direct, and completely jargon-free. Always begin with bullet summaries.',
    checklist: [],
    isPinned: true,
    colorName: 'purple',
    createdAt: '2026-06-07',
    updatedAt: '2026-06-07',
  },
  {
    id: 'note-4',
    title: '🌿 Mindful Breaks Scheduled',
    content: 'Hydrate well and stretch every two hours. Keeps team focus locked in!',
    checklist: [
      { id: 'sub-7', text: '10-minute diaphragmatic recovery breathing', isCompleted: true },
    ],
    isPinned: false,
    colorName: 'emerald',
    createdAt: '2526-06-05',
    updatedAt: '2026-06-05',
  },
];
